version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  test:
    docker:
    - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Setup env and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
  build_and_push:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
          name: Build and push Docker image
          command: |
            TAG=${CIRCLE_SHA1:0:10}
            docker build -t jaykoo/${HEROKU_APP_NAME}:$TAG:$TAG .
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
            docker push jaykoo/${HEROKU_APP_NAME}:$TAG
  
  deploy-dev:
    machine: true
    steps:
        - checkout
        - run:
            name: Build and push Docker image to Heroku
            command: |
              sudo curl https://cli-assets.heroku.com/install.sh | sh
              heroku container:login
              heroku auth:token
              HEROKU_API_KEY=$HEROKU_API_KEY heroku container:push -a $HEROKU_APP_NAME --recursive
              HEROKU_API_KEY=$HEROKU_API_KEY heroku container:release -a $HEROKU_APP_NAME web


workflows:
  heroku_deploy:
    jobs:
      - test
      - build_and_push:
          requires:
            - test
      - deploy-dev:
          requires:
            - build_and_push

          # filters:
          #   branches:
          #     only: master
      # - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
      #     requires:
      #       - build_and_push
          # filters:
          #   branches:
          #     only: master
      # - deploy:
      #     requires:
      #       - build_and_push
          # filters:
          #   branches:
          #     only: master
