version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

workflows:
  heroku_deploy:
    jobs:
      - test:
      - build_and_push:
          requires:
            - test
          # filters:
          #   branches:
          #     only: master
      # - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
      #     requires:
      #       - build_and_push
          # filters:
          #   branches:
          #     only: master
      - deploy:
          requires:
            - build_and_push
          # filters:
          #   branches:
          #     only: master

jobs:
  test:
    docker:
    - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Setup env and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
  
  build_and_push:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            TAG=${CIRCLE_SHA1:0:10}
            docker build -t jaykoo/final_app:$TAG .
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
            docker push jaykoo/final_app:$TAG
  deploy:
    executor: heroku/default
    steps:
      - run: bash .circleci/setup-heroku.sh
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4'
      - heroku/install
      - heroku/deploy-via-git:
          force: true
