version: 2.1

jobs:
  first-job:
    docker:
      - image: ubuntu
    steps:
      - run: echo "this is the first job"
  second-job:
    docker:
      - image: ubuntu
    steps:
      - run: echo "this is the second job"
  third-job:
    docker:
      - image: ubuntu
    steps:
      - run: echo "this is the third job"

workflows:
  first-workflow:
    jobs:
      - first-job
      - second-job:
          requires:
            - first-job
          filters:
            branches:
              only:
                - /.*special/
      - third-job:
          requires:
            - first-job
            - second-job