version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy:
    jobs:
      - test
      - build_and_push:
          requires:
            - test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - test
            - build_and_push

jobs:
  test:
    docker:
    - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Setup env and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
  
  build_and_push:
    docker:
      - image: circleci/python:3.6
        # auth:
        #   username: $DOCKER_HUB_USERNAME
        #   password: $DOCKER_HUB_PASSWORD  # context / project UI env-var reference
    steps:
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            TAG=0.1$CIRCLE_BUILD_NUM
            docker build -t jaykoo/final_app:$TAG .
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
            docker push jaykoo/final_app:$TAG