version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
  build_push_docker_image:
    docker:
        - image: circleci/python:3.6
    steps:
        - checkout
        - restore_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
        - run:
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
        - save_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            paths:
              - "venv"
        - setup_remote_docker
        - docker/check
        - docker/build:
            image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
            extra_build_args: "-t $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME"
            tag: 0.1.<< pipeline.number >>             
        - docker/push:
            image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
            tag: "latest"
        - docker/push:
            image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
            tag: "0.1.<< pipeline.number >>"
workflows:
  build_and_test:
    jobs:
      - build
      - test
